22.10.2019 14:00:45 Checking for system tray...
22.10.2019 14:00:45 Starting pgAdmin4 server...
22.10.2019 14:00:45 Creating server object, port:50171, key:03734064-9e57-4ec1-9180-bfc033322de5, logfile:C:/Users/hp/.pgAdmin4.1057243102.log
22.10.2019 14:00:45 Python Path: C:/Program Files/PostgreSQL/12/pgAdmin 4/venv/Lib/site-packages;C:/Program Files/PostgreSQL/12/pgAdmin 4/venv/DLLs;C:/Program Files/PostgreSQL/12/pgAdmin 4/venv/Lib
22.10.2019 14:00:45 Python Home: C:/Program Files/PostgreSQL/12/pgAdmin 4/venv
22.10.2019 14:00:45 Initializing Python...
22.10.2019 14:00:45 Python initialized.
22.10.2019 14:00:45 Adding new additional path elements
22.10.2019 14:00:45 Redirecting stderr...
22.10.2019 14:00:45 stderr redirected successfully.
22.10.2019 14:00:45 Initializing server...
22.10.2019 14:00:45 Webapp Path: C:/Program Files/PostgreSQL/12/pgAdmin 4/web/pgAdmin4.py
22.10.2019 14:00:45 Server initialized.
22.10.2019 14:00:45 Starting Server Thread...
22.10.2019 14:00:45 Open the application code and run it.
22.10.2019 14:00:45 Set the port number, key and force SERVER_MODE off
22.10.2019 14:00:45 PyRun_SimpleFile launching application server...
22.10.2019 14:00:46 Application Server URL: http://127.0.0.1:50171/?key=03734064-9e57-4ec1-9180-bfc033322de5
22.10.2019 14:00:46 The server should be up, we'll attempt to connect and get a response. Ping the server
22.10.2019 14:01:01 Attempt to connect one more time in case of a long network timeout while looping
22.10.2019 14:01:01 Everything works fine, successfully started pgAdmin4.
